### ISSUE TITLE
Link in readme to history gives 404

### ISSUE THREAD

**Issue by BSVogler** [rubberduck203/Evolve#1]

**Comment by rubberduck203** [comment]
Thanks for reporting this. The original website is in the evolve4www directory. You should be able to download it and browse the files locally.

**Comment by rubberduck203** [comment]
I was actually able to find a copy of the site on the way back machine. I'll see what I can do to update the links. 

http://web.archive.org/web/20130521121416/http://www.stauffercom.com/evolve4/

**Comment by ilyar** [comment]
maybe setup github pages for folder `evolve4www/help`

**Comment by rubberduck203** [comment]
That’s a really good idea. I’ve never used Github Pages before. Can it serve plain old html?

**Comment by ilyar** [comment]
@rubberduck203 see https://github.com/rubberduck203/Evolve/pull/3

**Comment by rubberduck203** [comment]
Fixed by #5
